controller:
  resources:
   limits:
     cpu: 200m
     memory: 800Mi
   requests:
     cpu: 50m
     memory: 250Mi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: "cicd-services"
              operator: In
              values:
              - "true"
repoServer:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: "cicd-services"
              operator: In
              values:
              - "true"
  resources:
   limits:
     cpu: 50m
     memory: 200Mi
   requests:
     cpu: 10m
     memory: 100Mi


notifications:
  resources:
   limits:
     cpu: 50m
     memory: 128Mi
   requests:
     cpu: 10m
     memory: 50Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: "cicd-services"
              operator: In
              values:
              - "true"

server:
  resources:
   limits:
     cpu: 200m
     memory: 200Mi
   requests:
     cpu: 50m
     memory: 100Mi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: "cicd-services"
              operator: In
              values:
              - "true"

redis:
  resources:
   limits:
     cpu: 200m
     memory: 150Mi
   requests:
     cpu: 50m
     memory: 75Mi


  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: "cicd-services"
              operator: In
              values:
              - "true"

dex:
  resources:
   limits:
     cpu: 200m
     memory: 150Mi
   requests:
     cpu: 20m
     memory: 50Mi


  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: "cicd-services"
              operator: In
              values:
              - "true"

applicationSet:
  resources:
   limits:
     cpu: 200m
     memory: 150Mi
   requests:
     cpu: 20m
     memory: 50Mi


  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: "cicd-services"
              operator: In
              values:
              - "true"
